import { StyleSheet, Text, View } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f6fa',
    justifyContent: "center",
    alignItems: 'center',
  },
  texto: {
    color: '#2f3640',
    fontSize: 25,
    textAlign: 'center',
  },
  legenda: {
    color: 'blue',
    fontSize: 18,
  },
  button: {
    backgroundColor: '#c23616',
    alignItems: 'center',
    justifyContent: 'center',
    width: 200,
    height: 50,
    padding: 20,
    marginTop: 10,
    borderRadius: 20,
  },
  imagem: {
    width: 300,
    height: 300,
    borderRadius: 30,
    marginBottom: 50,
    opacity: 0.8,
  },
  caixa: {
    width: 200,
    backgroundColor: 'white',
    fontSize: 20,
    padding: 10,
    marginTop: 10,
    borderRadius: 15,
  },
  textButton: {
    fontSize: 20,
    color: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '500',
  },
  link: {
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textLink: {
    marginTop: 10,
    fontSize: 15,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#0097e6',
    fontWeight: '600',
  },
  titulo: {
    fontWeight: '600',
    color: '#2f3640',
    fontSize: 22,
    textAlign: 'center',
  },
  secao: {
    height: 28,
    fontWeight: '500',
    color: 'white',
    backgroundColor: '#44bd32',
    fontSize: 18,
    textAlign: 'center',
    alignSelf: 'stretch',
    marginVertical: 10,
  },
  secaoTamanho: {
    flex: 0.8,
    flexDirection: 'row',
    alignSelf: 'stretch',
  },
  secaoSabores: {
    flex: 1,
    width: 'stretch',
    flexDirection: 'row',
    alignSelf: 'stretch',
  },
  opcao: {
    flex: 1,
    marginHorizontal: 4,
    marginVertical: 3,
    backgroundColor: '#dcdde1',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
  },
  opcaoSelecionado: {
    flex: 1,
    marginHorizontal: 4,
    marginVertical: 3,
    backgroundColor: '#7f8fa6',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
  },
  textOpcao: {
    fontSize: 16,
    color: '#2f3640',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '500',
  },
  textOpcaoSelecionado: {
    fontSize: 14,
    color: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '500',
  },
  buttonPedido: {
    backgroundColor: '#c23616',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginHorizontal: 3,
    height: 50,
    padding: 16,
    borderRadius: 20,
  },
});

export default styles;